services:
  web-predeploy:
    environment:
      TEST_AUTH: true
      BETTER_AUTH_SECRET: dev-secret
      BETTER_AUTH_URL: http://localhost:5260
  db-studio:
    ports:
      - 5261:4983
  web:
    environment:
      TEST_AUTH: true
      BETTER_AUTH_SECRET: dev-secret
      BETTER_AUTH_URL: http://localhost:5260
    ports:
      - 5260:3000
