services:
  db-studio:
    ports:
      - 4983:4983
  web:
    environment:
      AUTH_DEV_MAGIC_LINK: true
      BETTER_AUTH_SECRET: dev-secret
      BETTER_AUTH_URL: http://localhost:5260
    ports:
      - 5260:3000
